version: "3"
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
